# Generated by Django 4.2 on 2023-10-15 11:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('employees', models.ManyToManyField(blank=True, related_name='teams', to='employees.employee')),
                ('projects', models.ManyToManyField(related_name='teams', to='projects.project')),
            ],
        ),
    ]
